<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403235116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chofer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dni VARCHAR(20) NOT NULL, cuil VARCHAR(25) NOT NULL, telefono VARCHAR(30) DEFAULT NULL, tasa_personal NUMERIC(5, 2) DEFAULT NULL, tiene_deuda BOOLEAN NOT NULL, eliminado BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F7E3FEEDB38439E ON chofer (usuario_id)');
        $this->addSql('CREATE TABLE configuracion_sistema (id INT NOT NULL, tasa_global NUMERIC(5, 2) NOT NULL, dias_cobro_normal INT NOT NULL, plazo_acreditacion_horas INT NOT NULL, emails_notificacion_admin JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE factura (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_factura VARCHAR(30) NOT NULL, monto_bruto NUMERIC(12, 2) NOT NULL, monto_nota_credito NUMERIC(12, 2) DEFAULT NULL, monto_neto NUMERIC(12, 2) NOT NULL, fecha_emision DATE NOT NULL, fecha_cobro_estimada DATE NOT NULL, estado VARCHAR(40) NOT NULL, opcion_cobro VARCHAR(10) NOT NULL, archivo_factura_url VARCHAR(500) DEFAULT NULL, archivo_nota_credito_url VARCHAR(500) DEFAULT NULL, eliminado BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chofer_id INT NOT NULL, proforma_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F9EBA0092A5E4E82 ON factura (chofer_id)');
        $this->addSql('CREATE INDEX IDX_F9EBA009B26BFE8D ON factura (proforma_id)');
        $this->addSql('CREATE TABLE historial_tasa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tasa NUMERIC(5, 2) NOT NULL, tipo VARCHAR(20) NOT NULL, fecha_vigencia TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_responsable VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chofer_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B03078682A5E4E82 ON historial_tasa (chofer_id)');
        $this->addSql('CREATE TABLE invitacion_chofer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, token VARCHAR(64) NOT NULL, expira_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usado BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D4B6356C5F37A13B ON invitacion_chofer (token)');
        $this->addSql('CREATE TABLE proforma (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, periodo VARCHAR(20) NOT NULL, monto NUMERIC(12, 2) NOT NULL, tasa_aplicada NUMERIC(5, 2) NOT NULL, fecha_vencimiento DATE NOT NULL, descripcion TEXT DEFAULT NULL, estado VARCHAR(20) NOT NULL, eliminado BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chofer_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8383AFD62A5E4E82 ON proforma (chofer_id)');
        $this->addSql('CREATE TABLE solicitud_adelanto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tasa_aplicada NUMERIC(5, 2) NOT NULL, monto_bruto NUMERIC(12, 2) NOT NULL, monto_descontado NUMERIC(12, 2) NOT NULL, monto_neto NUMERIC(12, 2) NOT NULL, estado VARCHAR(20) NOT NULL, tipo_aprobacion VARCHAR(20) DEFAULT NULL, fecha_solicitud TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_aprobacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha_pago TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, motivo_rechazo TEXT DEFAULT NULL, aprobado_por VARCHAR(200) DEFAULT NULL, comprobante_pago_url VARCHAR(500) DEFAULT NULL, consentimiento_ip VARCHAR(50) NOT NULL, consentimiento_fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, factura_id INT NOT NULL, chofer_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF7780ADF04F795F ON solicitud_adelanto (factura_id)');
        $this->addSql('CREATE INDEX IDX_CF7780AD2A5E4E82 ON solicitud_adelanto (chofer_id)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100) NOT NULL, roles JSON NOT NULL, contrasena VARCHAR(255) NOT NULL, habilitado BOOLEAN NOT NULL, ultima_conexion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, eliminado BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2265B05DE7927C74 ON usuario (email)');
        $this->addSql('ALTER TABLE chofer ADD CONSTRAINT FK_1F7E3FEEDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0092A5E4E82 FOREIGN KEY (chofer_id) REFERENCES chofer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009B26BFE8D FOREIGN KEY (proforma_id) REFERENCES proforma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE historial_tasa ADD CONSTRAINT FK_B03078682A5E4E82 FOREIGN KEY (chofer_id) REFERENCES chofer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE proforma ADD CONSTRAINT FK_8383AFD62A5E4E82 FOREIGN KEY (chofer_id) REFERENCES chofer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE solicitud_adelanto ADD CONSTRAINT FK_CF7780ADF04F795F FOREIGN KEY (factura_id) REFERENCES factura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE solicitud_adelanto ADD CONSTRAINT FK_CF7780AD2A5E4E82 FOREIGN KEY (chofer_id) REFERENCES chofer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chofer DROP CONSTRAINT FK_1F7E3FEEDB38439E');
        $this->addSql('ALTER TABLE factura DROP CONSTRAINT FK_F9EBA0092A5E4E82');
        $this->addSql('ALTER TABLE factura DROP CONSTRAINT FK_F9EBA009B26BFE8D');
        $this->addSql('ALTER TABLE historial_tasa DROP CONSTRAINT FK_B03078682A5E4E82');
        $this->addSql('ALTER TABLE proforma DROP CONSTRAINT FK_8383AFD62A5E4E82');
        $this->addSql('ALTER TABLE solicitud_adelanto DROP CONSTRAINT FK_CF7780ADF04F795F');
        $this->addSql('ALTER TABLE solicitud_adelanto DROP CONSTRAINT FK_CF7780AD2A5E4E82');
        $this->addSql('DROP TABLE chofer');
        $this->addSql('DROP TABLE configuracion_sistema');
        $this->addSql('DROP TABLE factura');
        $this->addSql('DROP TABLE historial_tasa');
        $this->addSql('DROP TABLE invitacion_chofer');
        $this->addSql('DROP TABLE proforma');
        $this->addSql('DROP TABLE solicitud_adelanto');
        $this->addSql('DROP TABLE usuario');
    }
}
