<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260405150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create archivo table for storing uploaded files in PostgreSQL';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE archivo (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            nombre VARCHAR(255) NOT NULL,
            mime_type VARCHAR(100) NOT NULL,
            contenido BYTEA NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DROP TABLE IF EXISTS archivo");
    }
}
